#%RAML 1.0 DataType
type: object
displayName: ServiceFee
properties:
  serviceFee:
      description: New service fee to configure
      required: true
      type: number
      minimum: 0
      maximum: 15
