#%RAML 1.0 DataType
type: object
displayName: Transactions
uses:
  types: ../../libraries/types.raml
properties:
  timestamp:
      description: Date and time of transactions
      type: datetime
  from:
      description: Origin of transaction
      type: string
  to:
      description: Destination of transaction
      type: string
  total:
      description: Total of transaction
      type: types.Price
  reason:
      description: Explanation of transaction
      enum: [STAY_BOOKED, STAY_COMPLETED, STAY_CANCELED]
